// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqdgxynuqfksgdfjddw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcWRneHludXFma3NnZGZqZGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjUyMDIsImV4cCI6MjA2NDY0MTIwMn0.6m5U8InPvUXQx53pZ98cgTYq9wGMeCp4FgaJkFzWKjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);